services:
  proxy:
    image: traefik:v2.9
    command: --providers.docker --api.insecure --api.dashboard
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    

  redirector:
    build: ./
    volumes:
      - ./redirector:/var/www/html
    labels:
      traefik.http.routers.redirector.rule: Host(`localhost`)
    

  landing-page:
    build: ./
    volumes:
      - ./landing-page:/var/www/html
    labels:
      traefik.http.routers.landing.rule: Host(`tools.localhost`)

  controller:
    image: node:lts-alpine
    command: yarn dev
    working_dir: /usr/local/app
    ports:
      - 3000:3000
    volumes:
      - ./controller:/usr/local/app
      - $HOME/.yarn:/root/.yarn
    environment:
      YARN_CACHE_FOLDER: /root/.yarn
    labels:
      traefik.http.routers.controller.rule: Host(`tools.localhost`) && PathPrefix(`/controller`)
      traefik.http.services.controller.loadbalancer.server.port: 3000

  hymns:
    build: ./
    volumes:
      - ./hymns:/var/www/html
    labels:
      traefik.http.routers.hymns.rule: Host(`hymns.localhost`)

  docs:
    image: ghcr.io/afritzler/mkdocs-material
    volumes:
      - ./docs:/docs
    labels:
      traefik.http.routers.docs.rule: Host(`tools.localhost`) && (PathPrefix(`/docs`) || PathPrefix(`/livereload`))
      traefik.http.services.docs.loadbalancer.server.port: 8000
