name: Deploy hymns

on:
  push:
    paths:
      - hymns/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          USER: ${{secrets.DEPLOY_USER}}
          SOURCE: ./hymns/*
          TARGET: ${{secrets.HYMNS_SOURCE_LANDING_PAGE}}
          ARGS_MORE: --exclude=/controller/ --exclude=/docs/
