name: Deploy landing page

on:
  push:
    paths:
      - landing-page/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          USER: ${{secrets.DEPLOY_USER}}
          SOURCE: ./landing-page/*
          TARGET: ${{secrets.DEPLOY_SOURCE_LANDING_PAGE}}
          ARGS_MORE: --exclude=/controller/ --exclude=/docs/
