name: Build and deploy controller

on:
  push:
    paths:
      - controller/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: controller/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: ./controller
      - run: yarn build
        working-directory: ./controller
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          USER: ${{secrets.DEPLOY_USER}}
          SOURCE: ./controller/build/*
          TARGET: ${{secrets.DEPLOY_SOURCE_LANDING_PAGE}}/controller
